 gems: [jekyll-coffeescript, jekyll-watch, jekyll-assets]
 # This will require each of these gems automatically.
 
 gem install jekyll-coffeescript jekyll-watch jekyll-assets

 group :jekyll_plugins do
   gem "my-jekyll-plugin"
   gem "another-jekyll-plugin"
 end
 
  bundle install

gem update github-pages
